server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: smartrec-backend
  profiles:
    active: dev

  # 1. CSDL PostgreSQL
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smartrec_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 2. Redis Configuration (Message Broker)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # 3. Giới hạn upload file lớn (Chunked Upload support)
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

 # 4. Custom JWT Configuration (Thay thế hoàn toàn Keycloak)
jwt:
  # Chuỗi khóa bí mật (Secret Key) - Dùng 1 chuỗi Hex 256-bit dài để bảo mật
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  # Thời gian sống của Token: 86400000 milliseconds = 24 giờ
  expiration: ${JWT_EXPIRATION:86400000}
# 5. MinIO Object Storage Configuration
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET:smartrec-media}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}
